### ISSUE TITLE
max-nbs-frac

### ISSUE THREAD

**Issue by erikdassi** [HuntsmanCancerInstitute/RBSSeqTools#1]
Dear all,
I just noticed that setting max-nbs-frac in ScorePseudouridinePositions.java has no effect (it is always 0.01 even when setting it differently).
I noticed that in the file, it is correctly referred to as max-nbs-frac in line 972 - but then always referred to as min-nbs-frac (e.g. lines 1046), effectively disallowing setting this parameter to anything other than its default.
Could you fix that?
many thanks

**Comment by tmosbruger** [comment]
Thanks very much for letting us know about this issue, the code has been fixed.
